import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import os from 'node:os';
import {pathToFileURL} from 'node:url';
import {chromium} from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
const base=path.resolve('.cache/task-kit-acceptance'), kit=path.join(base,'composed-kit'), out=path.join(base,'composed-output'), review=path.join(base,'composed-review');
const read=(p)=>fs.readFileSync(p,'utf8'), json=p=>JSON.parse(read(p)), hash=p=>'sha256-'+crypto.createHash('sha256').update(fs.readFileSync(p)).digest('base64');
const manifest=json(path.join(kit,'KIT.json')), lock=json(path.join(out,'theme.lock.json')), originalLock=json(path.join(kit,'theme.lock.json')), tokens=json(path.join(kit,'tokens.subset.json')).tokens;
const checks=[]; const check=(name,passed,details={})=>{checks.push({name,outcome:passed?'passed':'failed',...details});};
const candidateHashes=Object.fromEntries(['result.html','deviations.md','theme.lock.json'].map(f=>[f,hash(path.join(out,f))]));
for(const [f,h] of Object.entries(manifest.files)) check('kit digest: '+f,hash(path.join(kit,f))===h);
for(const [f,h] of Object.entries(manifest.source.inputs)) if(fs.existsSync(path.join(kit,f))) check('available upstream source: '+f,hash(path.join(kit,f))===h);
for(const [f,h] of Object.entries(lock.exports)) check('lock upstream digest: '+f,h===manifest.source.inputs[f] && h===originalLock.exports[f]);
for(const k of ['schemaVersion','theme','version','ref','revision','profile','integration','resolvedAt','components']) check('lock identity: '+k,JSON.stringify(lock[k])===JSON.stringify(originalLock[k]));
function schemaCheck(v,s,p='$'){if(s.type){const a=Array.isArray(s.type)?s.type:[s.type],t=v===null?'null':Array.isArray(v)?'array':typeof v;if(!a.includes(t))throw Error(p+' type');}if(s.const!==undefined&&v!==s.const)throw Error(p+' const');if(s.enum&&!s.enum.includes(v))throw Error(p+' enum');if(s.pattern&&!new RegExp(s.pattern).test(v))throw Error(p+' pattern');if(s.minLength&&v.length<s.minLength)throw Error(p+' length');if(s.format==='date-time'&&!Number.isFinite(Date.parse(v)))throw Error(p+' timestamp');if(Array.isArray(v))v.forEach((x,i)=>schemaCheck(x,s.items,p+'['+i+']'));else if(v&&typeof v==='object'){for(const k of s.required??[])if(!(k in v))throw Error(p+' required '+k);for(const [k,x]of Object.entries(v)){if(s.propertyNames)schemaCheck(k,s.propertyNames,p);const child=s.properties?.[k];if(child)schemaCheck(x,child,p+'.'+k);else if(s.additionalProperties===false)throw Error(p+' extra '+k);else if(typeof s.additionalProperties==='object')schemaCheck(x,s.additionalProperties,p+'.'+k);}}}
try{schemaCheck(lock,json(path.join(kit,'schemas/json/theme.lock.schema.json')));check('lock schema',true);}catch(e){check('lock schema',false,{error:e.message});}
const html=read(path.join(out,'result.html'));
const declarations=[...html.matchAll(/(--[a-z0-9-]+):\s*([^;{}]+);/g)];
const roleByVar=Object.fromEntries(Object.entries(tokens).map(([r,t])=>['--'+r.replaceAll('.','-'),{r,...t}]));
for(const [_,name,value] of declarations){if(roleByVar[name])check('literal role '+name,value.trim()===roleByVar[name].css,{actual:value.trim(),expected:roleByVar[name].css});}
check('attribution retained',html.includes('CC BY 4.0')&&html.includes('Permission is hereby granted'));
check('pending decisions disclosed',read(path.join(out,'deviations.md')).includes('D-007')&&read(path.join(out,'deviations.md')).includes('D-008'));
const browser=await chromium.launch({headless:true});
const context=await browser.newContext({viewport:{width:1000,height:800}}); const page=await context.newPage(); const errors=[],requests=[];
page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(!r.url().startsWith('file:'))requests.push(r.url());});
await page.goto(pathToFileURL(path.join(out,'result.html')).href);
const active=()=>page.evaluate(()=>document.activeElement.id);
const css=async(sel,prop,pseudo=null)=>page.locator(sel).evaluate((el,{prop,pseudo})=>getComputedStyle(el,pseudo).getPropertyValue(prop),{prop,pseudo});
const role=async(sel,prop,r,pseudo=null)=>{const expected=await page.evaluate(({v,prop})=>{const x=document.createElement('span');x.style.setProperty(prop,v);document.body.append(x);const result=getComputedStyle(x).getPropertyValue(prop);x.remove();return result;},{v:tokens[r].css,prop});check(sel+' '+prop+' '+r,await css(sel,prop,pseudo)===expected,{expected,actual:await css(sel,prop,pseudo)});};
await role('body','background-color','color.surface.canvas');await role('.text-field-root','border-top-color','color.border.control');await role('#save','background-color','color.action.primary.bg');await role('#notifications','border-top-color','color.border.control');
await page.keyboard.press('Tab');check('Tab reaches native text field',await active()==='display-name');await role('.text-field-root','outline-color','color.interaction.focus.ring');check('field ring geometry',await css('.text-field-root','outline-style')==='dashed'&&await css('.text-field-root','outline-width')==='1px'&&await css('.text-field-root','outline-offset')==='-2px');
await page.keyboard.type('Independent name');await page.keyboard.press('Home');await page.keyboard.type('A ');check('native text editing',await page.inputValue('#display-name')==='A Independent name');
await page.keyboard.press('Tab');check('Tab reaches checkbox',await active()==='notifications');await role('#notifications','outline-color','color.interaction.focus.ring');await page.keyboard.press('Space');check('native Space toggles checkbox',await page.isChecked('#notifications'));await role('#notifications','outline-color','color.interaction.focus.ring-container');await role('#notifications','background-color','color.action.primary.bg');check('checked glyph visible',await page.locator('.checkbox-control svg').isVisible());check('checkbox does not modify text',await page.inputValue('#display-name')==='A Independent name');
await page.keyboard.press('Tab');check('Tab reaches Save',await active()==='save');await role('#save','outline-color','color.interaction.focus.ring-container');
const axe=[];async function scan(state){const result=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21a','wcag21aa','wcag22aa']).analyze();axe.push({state,violations:result.violations,incomplete:result.incomplete.map(x=>({id:x.id,impact:x.impact,nodes:x.nodes.length})),passes:result.passes.length});check('axe '+state,result.violations.length===0,{violations:result.violations.map(x=>x.id)});}
await scan('form filled checked');await page.keyboard.press('Enter');check('Save opens native modal',await page.locator('#confirmation').evaluate(e=>e.open&&e.matches(':modal')));check('initial focus Close',await active()==='close');await role('#confirmation','background-color','color.surface.overlay');await role('#confirmation','border-top-color','color.border.overlay');await role('#confirmation','background-color','color.surface.backdrop','::backdrop');
await page.keyboard.press('Shift+Tab');check('reverse Tab wraps Confirm',await active()==='confirm');await page.keyboard.press('Tab');check('forward Tab wraps Close',await active()==='close');await page.keyboard.press('Tab');check('Tab Close to Cancel',await active()==='cancel');await page.keyboard.press('Tab');check('Tab Cancel to Confirm',await active()==='confirm');await page.locator('#display-name').evaluate(e=>e.focus());check('native modal keeps background inert',await active()==='confirm');await scan('modal open');
const status=await page.textContent('#status');await page.keyboard.press('Escape');await page.waitForFunction(()=>!document.querySelector('#confirmation').open&&document.activeElement.id==='save');check('Escape closes and returns focus',true);check('Escape preserves status and draft',await page.textContent('#status')===status&&await page.inputValue('#display-name')==='A Independent name'&&await page.isChecked('#notifications'));
for(const id of ['cancel','close']){await page.keyboard.press('Enter');await page.locator('#'+id).focus();await page.keyboard.press('Space');await page.waitForFunction(()=>!document.querySelector('#confirmation').open&&document.activeElement.id==='save');check(id+' closes and returns focus',true);check(id+' preserves status',await page.textContent('#status')===status);}
await page.locator('#display-name').fill('<b>Sample & name</b>');await page.locator('#notifications').uncheck();await page.locator('#save').click();check('confirmation displays plain draft text',await page.textContent('#summary-name')==='<b>Sample & name</b>'&&await page.textContent('#summary-notifications')==='Disabled');await page.locator('#confirm').focus();await page.keyboard.press('Enter');await page.waitForFunction(()=>!document.querySelector('#confirmation').open&&document.activeElement.id==='save');check('Confirm updates only plain status', (await page.textContent('#status')).includes('<b>Sample & name</b>')&&await page.locator('#status b').count()===0);check('Confirm preserves inputs',await page.inputValue('#display-name')==='<b>Sample & name</b>'&&!await page.isChecked('#notifications'));
await page.setViewportSize({width:320,height:568});await page.locator('#display-name').fill('Long'.repeat(150));await page.locator('#save').click();check('narrow dialog and page fit horizontally',await page.evaluate(()=>{const r=document.querySelector('dialog').getBoundingClientRect();return document.documentElement.scrollWidth<=innerWidth&&r.left>=0&&r.right<=innerWidth;}));check('320px actions stack',await css('.dialog .actions','flex-direction')==='column');check('overflow body scrolls with visible actions',await page.evaluate(()=>{const e=document.querySelector('.dialog-body'),r=document.querySelector('#confirm').getBoundingClientRect();return e.scrollHeight>e.clientHeight&&r.bottom<=innerHeight&&r.top>=0;}));await scan('narrow long-content modal');await page.screenshot({path:path.join(review,'narrow-modal.png')});await page.keyboard.press('Escape');check('long confirmed status page fits',await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
await page.emulateMedia({reducedMotion:'reduce'});await page.locator('#save').click();check('reduced motion no meaningful duration',parseFloat(await css('#confirmation','animation-duration'))<=.00001);await page.keyboard.press('Escape');await page.emulateMedia({forcedColors:'active'});await page.locator('#save').focus();check('forced colors focus retained',await css('#save','outline-style')==='dashed'&&await css('#save','outline-width')==='1px');
const nojs=await browser.newContext({javaScriptEnabled:false,viewport:{width:320,height:568}});const np=await nojs.newPage();await np.goto(pathToFileURL(path.join(out,'result.html')).href);check('no JS Save hidden and explanation visible',!await np.locator('#save').isVisible()&&await np.locator('noscript p').isVisible());await np.locator('#display-name').fill('Native');await np.locator('#notifications').check();check('no JS native inputs work',await np.inputValue('#display-name')==='Native'&&await np.isChecked('#notifications'));await nojs.close();
check('no page errors',errors.length===0,{errors});check('no external requests',requests.length===0,{requests});
const environment={browser:'Chromium',version:browser.version(),playwright:json('node_modules/@playwright/test/package.json').version,axe:json('node_modules/@axe-core/playwright/package.json').version,os:os.platform()+' '+os.release(),node:process.version,headless:true,viewports:[{width:1000,height:800},{width:320,height:568}],profile:'default',density:'comfortable'};
await browser.close();check('candidate bytes unchanged',Object.entries(candidateHashes).every(([f,h])=>hash(path.join(out,f))===h));
fs.writeFileSync(path.join(review,'raw.json'),JSON.stringify({source:manifest.source.revision,kitDigest:hash(path.join(kit,'KIT.json')),candidateHashes,environment,checks,axe},null,2)+'\n');
console.log(JSON.stringify({checks:checks.length,failed:checks.filter(x=>x.outcome==='failed'),candidateHashes,environment},null,2));
