import { test, expect } from "./evidence-fixture.mjs";
import AxeBuilder from "@axe-core/playwright";
const annotation = { type: "verification", description: JSON.stringify({ component: "admin-form", category: "enhancements", states: ["default", "invalid", "busy"], variants: ["default"], note: "Local composed workflow: keyboard submit, summary navigation, correction, retained values, review, explicit busy completion, no data requests. Automated DOM/axe; no manual screen-reader or persistence claim." }) };
test("validation reference remains useful without JavaScript and fits narrow layouts", { annotation }, async ({ page }, info) => {
  await page.goto("patterns/validation-recovery/");
  for (const name of ["Normal", "Invalid", "Busy", "Success"]) await expect(page.getByRole("heading", { name, exact: true })).toBeVisible();
  if (info.project.name === "nojs") await expect(page.locator("[data-workflow]")).toBeHidden();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
});
test("correct and review with keyboard, preserve values, and explicitly complete the simulated save", { annotation }, async ({ page }, info) => {
  test.skip(info.project.name === "nojs", "Interactive workflow needs JavaScript; static protocol runs separately.");
  await page.goto("patterns/validation-recovery/");
  const root = page.locator("[data-workflow]"), requests = [];
  await expect(root).toBeVisible();
  page.on("request", request => requests.push({ method: request.method(), type: request.resourceType() }));
  await root.getByRole("textbox", { name: "Name required", exact: true }).fill("ws-07");
  await root.getByRole("textbox", { name: "Hostname required", exact: true }).fill("ws-07");
  await root.getByRole("textbox", { name: "Notes", exact: true }).fill("Preserve these notes");
  await root.getByRole("combobox", { name: "Role", exact: true }).selectOption("dev");
  await root.getByRole("checkbox").check();
  await root.getByRole("button", { name: "Review values", exact: true }).focus(); await page.keyboard.press("Enter");
  await expect(root.locator("[data-errors]")).toBeFocused();
  await expect(root.locator("[data-errors] a")).toHaveCount(2);
  await page.keyboard.press("Tab"); await page.keyboard.press("Enter");
  await expect(root.getByRole("textbox", { name: "Name required", exact: true })).toBeFocused();
  await page.keyboard.press("ControlOrMeta+A"); await page.keyboard.type("ws-08");
  await expect(root.locator("[data-status]")).toHaveText("2 fields need attention.");
  await page.keyboard.press("Tab"); await expect(root.getByRole("textbox", { name: "Hostname required", exact: true })).toBeFocused();
  await page.keyboard.press("ControlOrMeta+A"); await page.keyboard.type("ws-08");
  for (let stop = 0; stop < 4; stop++) await page.keyboard.press("Tab");
  await expect(root.getByRole("button", { name: "Review values", exact: true })).toBeFocused(); await page.keyboard.press("Enter");
  await expect(root).toHaveAttribute("data-stage", "review");
  await expect(root.locator("[data-review]")).toContainText("Preserve these notes");
  await page.keyboard.press("Shift+Tab"); await expect(root.getByRole("button", { name: "Edit values", exact: true })).toBeFocused(); await page.keyboard.press("Enter");
  await expect(root.getByRole("textbox", { name: "Notes", exact: true })).toHaveValue("Preserve these notes");
  await expect(root.getByRole("checkbox")).toBeChecked();
  for (let stop = 0; stop < 5; stop++) await page.keyboard.press("Tab");
  await expect(root.getByRole("button", { name: "Review values", exact: true })).toBeFocused(); await page.keyboard.press("Enter");
  await page.keyboard.press("Enter");
  await expect(root).toHaveAttribute("data-stage", "busy");
  await expect(root.locator("form")).toHaveAttribute("aria-busy", "true");
  await expect(root.getByRole("textbox", { name: "Name required", exact: true })).toBeDisabled();
  await page.keyboard.press("Enter");
  await expect(root).toHaveAttribute("data-stage", "success");
  await expect(root.locator("[data-status]")).toContainText("Nothing was sent or stored");
  expect(requests.filter(request => request.method !== "GET" || ["fetch", "xhr"].includes(request.type))).toEqual([]);
  if (info.project.name === "desktop") expect((await new AxeBuilder({ page }).include("[data-workflow]").analyze()).violations).toEqual([]);
  await root.getByRole("button", { name: "Reset values", exact: true }).click();
  await expect(root.getByRole("textbox", { name: "Notes", exact: true })).toHaveValue("");
});
