import { promises as fs } from "node:fs";
import index from "@j3w1/ui/index.json" with { type: "json" };
const common = new Set(["button", "text-field", "select", "textarea"]);
const loaders = index.components.map(({ id }) => `${JSON.stringify(id)}: () => Promise.all([import('@j3w1/ui/examples/${id}.json')${common.has(id) ? "" : `, import('@j3w1/ui/register/${id}'), import('@j3w1/ui/styles/${id}.css')`}]).then(([module]) => module.default)`);
await fs.mkdir(new URL("../src", import.meta.url), { recursive: true });
await fs.writeFile(new URL("../src/generated-loaders.js", import.meta.url), `// Generated by the demo build from the installed package index.\nexport const loaders = {\n${loaders.join(",\n")}\n};\n`);
