// Implementation metadata describes maintained APIs; design meaning stays in spec/.
export const definitions = {};
const property = (name, type, description, controller = false, readonly = false) => ({ name, type, description, controller, readonly });
const method = (name, signature, description) => ({ name, signature, description });
const event = (name, detail, description) => ({ name: `j3w1-${name}`, detail, description });
const common = {
  attributes: [{ name: "disabled", description: "Disable the native controls owned by this instance." }, { name: "loading", description: "Mark the primary control busy and prevent duplicate activation." }],
  properties: [property("disabled", "boolean", "Delegates disabled state to native children."), property("name", "string", "Native control name; application form keys remain explicit.")],
  methods: [method("refresh", "(): void", "Reconnect behavior after replacing native child structure."), method("focus", "(options?: FocusOptions): void", "Focus the first usable native control.")],
  events: [],
};
const define = (ids, module, behavior, extra = {}) => {
  for (const id of ids.split(" ")) {
    const api = extra.api ?? {};
    definitions[id] = { module, behavior, domReason: "Light DOM retains static content, native semantics, label relationships and host composition without duplicating controls.", ...extra, api: { attributes: [...common.attributes, ...(api.attributes ?? [])], properties: [...common.properties.filter(p => !(api.properties ?? []).some(own => own.name === p.name)), ...(api.properties ?? [])], methods: [...common.methods.filter(m => !(api.methods ?? []).some(own => own.name === m.name)), ...(api.methods ?? [])], events: api.events ?? [] } };
  }
};
define("button icon-button button-group", "native", "actions", { display: "inline-block", api: { attributes: [{ name: "tone", description: "Button tone: primary, secondary, tertiary or destructive." }], events: [event("action", "{ action: string; pressed: boolean }", "A native button activated. Prevent default on this event to cancel the associated native default action.")] } });
define("link field fieldset radio-group segmented-control breadcrumbs skip-link card list description-list badge kbd timeline skeleton loading-indicator progress", "native", "content");
define("text-field textarea select checkbox range number-field search-field date-picker time-picker", "native", "fields", { domReason: "Visible native controls retain FormData, labels, constraints, disabled fieldsets and reset. No duplicate form-value mechanism is installed.", api: {
  attributes: ["value", "required", "readonly", "checked"].map(name => ({ name, description: `Forwards ${name} to the primary native control.` })),
  properties: [property("value", "string", "Primary native value; assignment does not fabricate user events."), property("checked", "boolean", "Native checkbox state."), property("required", "boolean", "Native required constraint."), property("readOnly", "boolean", "Native readonly property."), property("form", "HTMLFormElement | null", "Owning native form.", false, true)],
  methods: [method("checkValidity", "(): boolean", "Check owned native constraints."), method("reportValidity", "(): boolean", "Report the first invalid owned control."), method("clear", "(): void", "Clear an editable primary input and emit native input/change.")],
  events: [event("change", "{ value: string; checked?: boolean; name: string }", "Native change from an owned control, alongside the original native event.")],
} });
definitions.checkbox.api.properties.push(property("indeterminate", "boolean", "Native mixed state; Space changes a mixed checkbox to checked.", true));
definitions.checkbox.api.properties.push(property("values", "string[]", "Values of checked native options in this instance.", true));
definitions.select.api.properties.push(property("values", "string[]", "Selected values of a multiple native select.", true));
definitions.select.domReason = "Theme-owned combobox/listbox presentation backed by the original native select for FormData, constraints, defaults and reset. The native control is visible only before enhancement or without JavaScript.";
for (const id of ['date-picker','time-picker']) definitions[id].domReason = "Theme-owned date/time editor and controls backed by the original native input for form values and constraints. Native input is the no-JavaScript fallback.";
for (const id of ["number-field", "text-field"]) definitions[id].api.methods.push(method("stepBy", "(amount: number): void", "Step a number input by the supplied number of native steps."));
define("switch", "native", "switchControl", { display: "inline-block", api: { attributes: ["checked", "value"].map(name => ({ name, description: `Default switch ${name}.` })), properties: [property("checked", "boolean", "Immediate switch state; a named switch exposes a matching native hidden form value.", true)], events: [event("change", "{ checked: boolean; value: string; name: string }", "The user toggled the switch.")] } });
define("file-input", "native", "fileInput", { api: { properties: [property("files", "File[]", "Current native files; files are never uploaded by the component.", true, true)], methods: [method("clear", "(): void", "Clear the current native file selection.")], events: [event("change", "{ value: string; name: string }", "Native file selection changed; read files from the component.")] } });
define("tabs", "navigation", "tabs", { api: { attributes: [{ name: "activation", description: "automatic (default) or manual activation when arrowing among tabs." }], properties: [property("selectedId", "string", "ID of the selected enabled tab.", true)], methods: [method("select", "(id: string, focus?: boolean): HTMLElement", "Select an enabled tab by its exact ID.")], events: [event("select", "{ id: string; panelId: string }", "The user selected a tab.")] } });
define("toolbar", "navigation", "toolbar", { api: { events: [event("action", "{ action: string; pressed: boolean }", "A toggle action changed.")] } });
define("sidebar-nav disclosure", "navigation", "disclosure", { api: { properties: [property("open", "boolean", "Native details expansion when this component contains details.", true)], events: [event("toggle", "{ id: string; expanded: boolean }", "A native disclosure or navigation group changed.")] } });
define("combobox", "navigation", "combobox", { api: { properties: [property("value", "string", "Typed or accepted input value.", true), property("open", "boolean", "List visibility.", true)], methods: [method("show", "(allOptions?: boolean): void", "Open the list, optionally showing every option."), method("hide", "(): void", "Close without discarding typed text.")], events: [event("change", "{ value: string; name: string }", "An option was accepted or the value cleared.")] } });
define("menu", "navigation", "menu", { api: { properties: [property("open", "boolean", "Menu visibility.", true)], methods: [method("show", "(): void", "Open and focus the first menu item."), method("hide", "(focus?: boolean): void", "Close all menus, optionally restoring the trigger.")], events: [event("action", "{ action: string; checked: boolean }", "An enabled action or check item was invoked.")] } });
define("dialog drawer", "overlays", "modal", { api: { properties: [property("open", "boolean", "Native modal state.", true), property("returnValue", "string", "Native dialog result.", true, true)], methods: [method("show", "(): void", "Open using native showModal and remember the opener."), method("close", "(value?: string): void", "Close with a result value.")], events: [event("open", "Record<string, never>", "The modal opened."), event("close", "{ returnValue: string }", "The modal closed and restored available opener focus."), event("cancel", "Record<string, never>", "Native cancel request; prevent default to keep the modal open."), event("action", "{ action: string }", "An explicit dialog action; prevent default to keep it open.")] } });
define("tooltip", "overlays", "tooltip", { display: "inline-block", api: { properties: [property("open", "boolean", "Current tooltip visibility.", true, true)], methods: [method("show", "(): void", "Show the description unless dismissed in this hover/focus session."), method("hide", "(): void", "Hide and cancel pending timers.")] } });
define("popover", "overlays", "popover", { api: { properties: [property("open", "boolean", "Non-modal panel visibility.", true)], methods: [method("show", "(): void", "Show next to the trigger."), method("hide", "(focus?: boolean): void", "Hide, optionally restoring trigger focus.")], events: [event("toggle", "{ expanded: boolean }", "The panel changed visibility.")] } });
define("alert toast empty-state error-state chip", "overlays", "feedback", { api: { methods: [method("dismiss", "(id?: string): void", "Dismiss a message; focused actions move to the next available control.")], events: [event("dismiss", "{ id: string }", "Cancelable message dismissal."), event("retry", "Record<string, never>", "Request recovery; the host owns the result."), event("action", "{ action: string }", "An explicit message action.")] } });
define("tree", "advanced", "tree", { api: { properties: [property("selectedId", "string", "Selected treeitem ID.", true)], methods: [method("expand", "(id: string, expanded?: boolean): void", "Expand or collapse a parent by ID.")], events: [event("select", "{ id: string }", "The user selected a visible enabled item."), event("toggle", "{ id: string; expanded: boolean }", "A parent expanded or collapsed.")] } });
define("multiselect", "advanced", "multiselect", { api: { properties: [property("values", "string[]", "Selected native checkbox values, including hidden matches.", true)], methods: [method("clear", "(): void", "Clear every selected value and report the explicit change.")], events: [event("selection", "{ values: string[] }", "The selected values changed through interaction.")] } });
define("repeater", "advanced", "repeater", { api: { attributes: [{ name: "max", description: "Maximum rows, default 10; positive integer up to 100." }], properties: [property("rowIds", "string[]", "Stable IDs in current source order.", true, true)], methods: [method("add", "(): string | null", "Append a row when below the configured limit."), method("remove", "(id: string): void", "Remove a known row and recover focus."), method("move", "(id: string, direction: number): void", "Move a row one position up or down.")], events: [event("rows", "{ ids: string[] }", "Row order or membership changed.")] } });
define("command-palette", "advanced", "commandPalette", { api: { attributes: [{ name: "shortcut", description: "Opt in to Ctrl+K / Cmd+K; absence leaves global shortcuts to the host." }], properties: [property("open", "boolean", "Native modal state.", true)], methods: [method("show", "(): void", "Open and focus the command prompt."), method("close", "(): void", "Close and restore the opener.")], events: [event("command", "{ action: string; href: string | null }", "Invoke the chosen command; prevent default to handle a result link yourself.")] } });
define("avatar", "display", "avatar", { display: "inline-block", api: { attributes: [{ name: "src", description: "Optional caller-owned image URL." }], properties: [property("src", "string", "Image URL; empty restores initials.", true)] } });
define("chart", "display", "chart", { api: { properties: [property("data", "Array<{ label: string; value: number }>", "Finite non-negative one-series data; at most 200 rows.", true)] } });
define("editor-search", "display", "editorSearch", { api: { properties: [property("source", "string", "Read-only literal source text.", true), property("query", "string", "Literal case-insensitive query.", true), property("matchCount", "number", "Current number of matches.", true, true)], methods: [method("next", "(direction?: number): void", "Move among existing matches without moving input focus.")] } });
define("code-editor terminal diff-view diagnostics", "display", "developerView", { api: { methods: [method("setText", "(text: string): void", "Replace the bounded read-only text view; no code or shell execution occurs.")], events: [event("action", "{ action: string }", "Request a developer-view action; editing and execution belong to the host.")] } });
define("table data-table filterable-table", "tables", "table", { api: { methods: [method("sort", "(column: number, direction?: 'ascending' | 'descending'): void", "Sort existing native rows by a column."), method("filter", "(query: string): void", "Filter existing rows by literal text.")], events: [event("sort", "{ column: number; direction: string }", "The user requested sorting."), event("selection", "{ ids: string[] }", "Selected row identities changed.")] } });
define("pagination", "tables", "pagination", { api: { properties: [property("page", "number", "Current page when using local button-mode pagination.", true)], events: [event("page", "{ page: number }", "Local page choice changed; native href links continue to navigate.")] } });
define("wizard", "forms", "wizard", { api: { properties: [property("step", "number", "Current zero-based step.", true)], methods: [method("next", "(): boolean", "Validate current native controls before advancing."), method("back", "(): void", "Return without validation.")], events: [event("step", "{ step: number }", "The active step changed."), event("complete", "Record<string, never>", "Final local validation succeeded; the host owns persistence.")] } });
define("form-builder", "form-builder", "formBuilder", { styles: ["button", "text-field", "textarea", "select", "checkbox", "radio-group", "alert", "table"], api: { methods: [method("exportDefinition", "(): string", "Export the canonical bounded definition without entered preview values."), method("importDefinition", "(json: string): boolean", "Validate and import a complete definition without partial mutation.")] } });
define("settings-panel admin-form", "forms", "formComposition", { styles: ["button", "field", "text-field", "checkbox", "radio-group", "select", "switch"], api: { events: [event("submit", "{ values: Array<[string, FormDataEntryValue]> }", "Validated local native form values; the host owns saving.")] } });
define("file-browser", "compositions", "fileBrowser", { dependencies: ["tree"], styles: ["table"], api: { events: [event("open-file", "{ id: string }", "Request opening an existing file identity.")] } });
define("compact-dashboard", "compositions", "dashboard", { dependencies: ["chart"], styles: ["table"], api: { events: [event("open-record", "{ id: string }", "Request an existing record.")] } });
define("i3-window-frame", "compositions", "windowFrame", { api: { events: [event("window-action", "{ action: string }", "Request a host window action; the browser component does not control OS windows.")] } });

// Composition dependencies are registered and copied with their parent.
definitions.breadcrumbs.module = "navigation"; definitions.breadcrumbs.behavior = "disclosure";
definitions.breadcrumbs.api.events = [event("toggle", "{ expanded: boolean }", "A collapsed breadcrumb group changed visibility.")];
definitions["data-table"].dependencies = ["menu"];
definitions.toolbar.dependencies = ["menu"];
definitions["filterable-table"].dependencies = ["search-field"];
definitions["filterable-table"].styles = ["data-table", "select", "table"];
definitions["settings-panel"].dependencies = ["switch"];
definitions["admin-form"].dependencies = ["text-field", "textarea", "select"];
definitions.wizard.styles = ["text-field"];
definitions["i3-window-frame"].styles = ["terminal", "code-editor", "tabs"];
definitions["form-builder"].extraStyles = ["site/src/styles/form-tools.css"];
definitions["admin-form"].extraStyles = ["site/src/styles/form-tools.css"];
definitions["form-builder"].api.properties.push(property("definitionJson", "string", "Validated bounded definition JSON; entered preview values are excluded.", true));
for (const id of ["data-table", "filterable-table"]) definitions[id].api.properties.push(property("selectedIds", "string[]", "Stable selected row IDs.", true));
