import { anchorFor } from "../../../../scripts/lib/anchors.mjs";
import { escapeHtml as esc } from "../../../../scripts/lib/hex-literals.mjs";

export function workflowMarkup(prefix) {
  return `<section class="admin-form form-tool" data-workflow="${esc(prefix)}" hidden><h2 class="admin-form-title">Try the local workflow</h2><p>Values stay in this page. Reset clears them. No save request is sent.</p><form novalidate><div class="alert alert-danger form-tool-summary" data-errors role="alert" tabindex="-1" hidden></div><fieldset class="form-tool-fields" data-fields aria-label="Enter values"></fieldset><div class="form-tool-actions"><button class="button" type="submit" data-event="submit">Review values</button></div></form><table data-review class="table" hidden></table><p data-status role="status" tabindex="-1" id="${anchorFor.formField(prefix, "workflow", "status")}"></p><div class="form-tool-actions"><button class="button" type="button" data-event="edit" hidden>Edit values</button><button class="button" type="button" data-event="confirm" hidden>Simulate save</button><button class="button" type="button" data-event="complete" hidden>Complete simulation</button><button class="button" type="button" data-event="reset">Reset values</button></div></section>`;
}

export function builderMarkup(prefix) {
  const id = name => anchorFor.uiExample(prefix, name);
  return `<section class="form-builder form-tool" data-builder hidden aria-label="Form definition editor">
<div class="form-builder-editor"><label for="${id("kind")}">Field type<select id="${id("kind")}" data-kind><option value="text">Text</option><option value="textarea">Textarea</option><option value="select">Select</option><option value="checkbox">Checkbox</option><option value="radio">Radio</option></select></label><button class="button" type="button" data-add>Add field</button><label for="${id("density")}">Preview density<select id="${id("density")}" data-density-choice><option value="compact">Compact</option><option value="comfortable">Comfortable</option></select></label></div>
<p data-builder-status role="status"></p><p data-empty>No fields yet. Choose a type and add your first field.</p><ol class="form-builder-list" data-field-list></ol>
<form class="form-builder-editor" data-editor novalidate hidden><h2>Edit selected field</h2><label for="${id("label")}">Field label<input id="${id("label")}" name="label" maxlength="120" required></label><label for="${id("help")}">Field help<textarea id="${id("help")}" name="help" maxlength="400"></textarea></label><label for="${id("required")}"><input id="${id("required")}" name="required" type="checkbox">Required field</label><label for="${id("options")}" data-options-label>Options JSON<textarea id="${id("options")}" name="options" rows="6" maxlength="65537" spellcheck="false"></textarea></label><p>Edit option IDs and labels as JSON. Keep each ID when changing its label. Select and radio fields need 1–20 options.</p><div class="form-tool-actions"><button class="button" type="submit">Save field definition</button><button class="button button-secondary" type="button" data-cancel>Cancel edit</button></div></form>
<h2>Preview</h2><p>Definition changes clear preview values. Review validates required values and choices.</p><div data-preview>${workflowMarkup(id("preview"))}</div>
<h2>Transfer definition</h2><p>Schema version 1 accepts at most 64 KiB and 20 fields. Invalid imports leave the current definition unchanged. Export excludes entered preview values.</p><div class="form-builder-editor"><label for="${id("json")}">Definition JSON<textarea id="${id("json")}" data-json rows="10" spellcheck="false" maxlength="65537"></textarea></label></div><div class="form-tool-actions"><button class="button" type="button" data-export>Show definition JSON</button><button class="button button-secondary" type="button" data-download>Download definition</button><button class="button button-secondary" type="button" data-import>Import definition JSON</button><button class="button button-secondary" type="button" data-reset>Reset builder</button></div></section><p>The bounded form editor requires JavaScript. Its definition is plain JSON with stable field IDs, labels, help, required flags and explicit option IDs.</p>`;
}
