<script setup>
import { computed, reactive, ref, watch } from 'vue';
import { useRoute } from 'vue-router';
import { state, notify } from '../store.js';
import UiSpecimen from '../UiSpecimen.vue';
const route=useRoute(),kind=computed(()=>route.params.kind),email=ref(''),password=ref(''),message=ref(''),help=ref(''),role=ref('Editor'),draft=reactive({...state.profile});
watch(kind,()=>{message.value='';password.value='';});
const articles=[['Install one component','Load the exact package version, token CSS, per-component styles and registration. Copy the maintained native markup.','../implement/'],['Use native forms','Native names, labels, fieldsets and constraints keep your application behavior explicit.','../components/text-field/'],['Prepare an agent kit','Select only the needed IDs and keep the complete copy closure and notices.','../agents/'],['Inspect keyboard behavior','Each component contract lists its exact focus, selection and keyboard rules.','../components/']];
const matches=computed(()=>articles.filter(row=>row.join(' ').toLowerCase().includes(help.value.toLowerCase())));
function authenticate(){message.value=kind.value==='recovery'?'Recovery request simulated locally. No email was sent.':'Sign-in validation passed locally. No session or authentication request was created.';password.value='';}
</script>
<template><header class="view-heading"><div><p class="eyebrow">WORKSPACE / PAGES</p><h1 tabindex="-1" style="text-transform:capitalize">{{ kind.replaceAll('-',' ') }}</h1><p>Application page compositions with explicit local boundaries.</p></div></header>
  <section v-if="kind==='profile'" class="panel"><div class="panel-heading"><div><span class="identity">JL</span><h2>{{ state.profile.name }}</h2><p>{{ state.profile.email }} · {{ state.profile.role }}</p></div><RouterLink to="/pages/settings">Edit profile →</RouterLink></div><div class="metrics"><article><span class="metric-label">Projects</span><strong class="metric">24</strong></article><article><span class="metric-label">Reviews</span><strong class="metric">148</strong></article><article><span class="metric-label">Contributions</span><strong class="metric">67</strong></article><article><span class="metric-label">Local workspace</span><strong class="metric">01</strong></article></div><UiSpecimen id="timeline" /></section>
  <form v-else-if="kind==='settings'" class="panel form-grid" @submit.prevent="Object.assign(state.profile,draft);notify('Profile settings saved in this local demo.')"><label>Display name<input v-model="draft.name" required maxlength="80"></label><label>Email address<input type="email" v-model="draft.email" required></label><label>Role label<select v-model="draft.role"><option>Viewer</option><option>Editor</option><option>Administrator</option></select></label><label>Demo notification preference<select :value="String(draft.notifications)" @change="draft.notifications=$event.target.value==='true'"><option value="true">Enabled</option><option value="false">Disabled</option></select></label><p class="wide muted">Role labels are demonstration data and do not grant permissions.</p><div class="actions wide"><j3w1-button><button class="button" type="submit">Save local settings</button></j3w1-button><button type="button" @click="Object.assign(draft,state.profile)">Discard changes</button></div></form>
  <section v-else-if="kind==='permissions'" class="panel"><div class="panel-heading"><h2>Role capability demonstration</h2><label>Preview role<select v-model="role"><option>Viewer</option><option>Editor</option><option>Administrator</option></select></label></div><div class="table-scroll"><table class="records-table"><thead><tr><th>Capability</th><th>Preview availability</th></tr></thead><tbody><tr v-for="[name,allowed] in [['Read records',true],['Edit records',role!=='Viewer'],['Manage members',role==='Administrator']]" :key="name"><th scope="row">{{ name }}</th><td>{{ allowed?'✓ Available':'— Unavailable' }}</td></tr></tbody></table></div><p class="muted">This is a presentation example. Your server must enforce real authorization independently of the UI.</p></section>
  <form v-else-if="['sign-in','recovery'].includes(kind)" class="panel stack account-form" @submit.prevent="authenticate"><h2>{{ kind==='recovery'?'Recover access':'Welcome to your workspace' }}</h2><p class="muted">Use synthetic values. No credentials leave this page.</p><label>Email address<input v-model="email" type="email" required autocomplete="off" placeholder="jordan@example.test"></label><label v-if="kind==='sign-in'">Demo password<input v-model="password" type="password" required minlength="8" autocomplete="off"></label><j3w1-button><button class="button" type="submit">{{ kind==='recovery'?'Simulate recovery':'Validate sign-in locally' }}</button></j3w1-button><RouterLink :to="kind==='recovery'?'/pages/sign-in':'/pages/recovery'">{{ kind==='recovery'?'Back to sign-in':'Forgot password?' }}</RouterLink><p role="status">{{ message }}</p></form>
  <div v-else-if="kind==='pricing'" class="gallery-grid"><article v-for="[name,price,features] in [['Personal','0',['One workspace','Core components','Local projects']],['Team','24',['Shared workspaces','Review workflows','Team templates']],['Organization','64',['Organization views','Policy controls','Priority planning']]]" :key="name" class="panel"><p class="eyebrow">SAMPLE PLAN</p><h2>{{ name }}</h2><p class="price">${{ price }}<small class="muted"> / month</small></p><ul><li v-for="feature in features" :key="feature">{{ feature }}</li></ul><button type="button" @click="notify(`${name} selected for this pricing demonstration. No purchase or subscription was created.`)">Preview {{ name }}</button><p class="muted">Illustrative pricing only.</p></article></div>
  <section v-else-if="kind==='help'"><div class="filters"><label>Search help<input v-model="help" type="search" placeholder="forms, package, keyboard…"></label></div><div class="gallery-grid"><a v-for="[title,text,url] in matches" :key="title" :href="url" class="panel gallery-link"><h2>{{ title }} →</h2><p>{{ text }}</p></a></div><p v-if="!matches.length">No help articles match this search.</p></section>
  <section v-else-if="kind==='error'" class="panel empty"><p class="eyebrow">SERVICE ERROR / DEMONSTRATION</p><h2>The sample request could not complete.</h2><p>Your local records are still available.</p><div class="actions"><button type="button" @click="message='Retry completed in the local simulation. No network request was sent.'">Retry locally</button><RouterLink to="/dashboards/analytics">Return to dashboard</RouterLink></div><p role="status">{{ message }}</p></section>
  <section v-else class="panel empty"><p class="eyebrow">404 / NOT FOUND</p><h2>This page is not in the workspace.</h2><p>Choose a destination from navigation or open the command prompt.</p><RouterLink to="/dashboards/analytics">Return to dashboard →</RouterLink></section>
</template>
<style scoped>.account-form { max-width:560px; margin-inline:auto; }.price small { font-size:12px; }li { margin-block:12px; }</style>
