<script setup>
import { computed, ref, nextTick } from 'vue';
import { useRoute } from 'vue-router';
import { state, notify, nextId } from '../store.js';
const route = useRoute(), kind = computed(() => route.params.kind);
const text = ref(''), selectedMail = ref(1), archived = ref(false), compose = ref(false), subject = ref(''), mailBody = ref(''), eventTitle = ref(''), day = ref(8), taskName = ref('');
const mails = computed(() => state.mail.filter(mail => mail.archived===archived.value));
const selected = computed(() => state.mail.find(mail => mail.id===selectedMail.value));
function sendChat() { if(!text.value.trim())return;state.messages.push({id:nextId(state.messages),person:'You',text:text.value.trim(),self:true});text.value='';notify('Message added to the local conversation.'); }
function sendMail() { state.mail.push({id:nextId(state.mail),from:'You',subject:subject.value,body:mailBody.value,read:true,archived:false});compose.value=false;subject.value='';mailBody.value='';notify('Message created locally. No email was sent.'); }
function addEvent() { state.events.push({id:nextId(state.events),day:Number(day.value),title:eventTitle.value});eventTitle.value='';notify('Event added to the local September calendar.'); }
function addTask() { if(!taskName.value.trim())return;state.tasks.push({id:nextId(state.tasks),name:taskName.value.trim(),status:'Ready'});taskName.value='';notify('Task added.'); }
async function move(task,status) { task.status=status;notify(`${task.name} moved to ${status}.`);await nextTick();document.querySelector(`[data-task-id="${task.id}"] select`)?.focus(); }
</script>
<template>
  <header class="view-heading"><div><p class="eyebrow">WORKSPACE / APPLICATIONS</p><h1 tabindex="-1" style="text-transform:capitalize">{{ kind }}</h1><p>Bounded local actions, with clear keyboard paths.</p></div></header>
  <div v-if="kind==='email'" class="split"><aside class="stack"><button type="button" @click="compose=true">+ Compose</button><label>Folder<select :value="archived ? 'archive' : 'inbox'" @change="archived=$event.target.value==='archive'"><option value="inbox">Inbox</option><option value="archive">Archive</option></select></label><button v-for="mail in mails" :key="mail.id" class="list-button" type="button" :aria-pressed="selectedMail===mail.id" @click="selectedMail=mail.id;mail.read=true;compose=false"><strong>{{ mail.subject }} {{ mail.read?'':'●' }}</strong><small class="block muted">{{ mail.from }}</small></button><p v-if="!mails.length">This folder is empty.</p></aside><form v-if="compose" class="panel stack" @submit.prevent="sendMail"><h2>Compose a local message</h2><label>Subject<input v-model="subject" required maxlength="120"></label><label>Message<textarea v-model="mailBody" required rows="8"></textarea></label><div class="actions"><button type="submit">Create local message</button><button type="button" @click="compose=false">Cancel</button></div></form><article v-else-if="selected" class="panel"><div class="panel-heading"><h2>{{ selected.subject }}</h2><button type="button" @click="selected.archived=!selected.archived;notify(selected.archived?'Message archived.':'Message returned to inbox.')">{{ selected.archived?'Move to inbox':'Archive' }}</button></div><p class="muted">From {{ selected.from }}</p><p>{{ selected.body }}</p><div class="actions"><button type="button" @click="compose=true;subject=`Re: ${selected.subject}`">Reply locally</button><button type="button" @click="selected.read=!selected.read">Mark {{ selected.read?'unread':'read' }}</button></div></article></div>
  <section v-else-if="kind==='chat'" class="panel"><div class="panel-heading"><h2>Design workspace</h2><span class="muted">2 participants · local fixture</span></div><div class="stack" role="log" aria-label="Conversation"><article v-for="message in state.messages" :key="message.id" :class="['message',{self:message.self}]"><small class="muted">{{ message.person }}</small><p>{{ message.text }}</p></article></div><form class="filters" @submit.prevent="sendChat"><label>Message<input v-model="text" required maxlength="1000" placeholder="Write a local message…"></label><button type="submit">Add message →</button></form></section>
  <template v-else-if="kind==='calendar'"><section class="panel"><div class="panel-heading"><h2>September 2026</h2><span class="muted">Fixed demonstration month</span></div><form class="filters" @submit.prevent="addEvent"><label>Event title<input v-model="eventTitle" required maxlength="80"></label><label>Day<input v-model="day" type="number" min="1" max="30" required></label><button type="submit">Add event</button></form><div class="calendar"><div v-for="date in 30" :key="date" class="calendar-day"><strong>{{ String(date).padStart(2,'0') }}</strong><button v-for="event in state.events.filter(event=>event.day===date)" :key="event.id" type="button" :aria-label="`Remove event: ${event.title}`" @click="state.events.splice(state.events.indexOf(event),1);notify('Local event removed.')">{{ event.title }} ×</button></div></div><p class="muted">Event buttons remove their local entry. No external calendar is connected.</p></section></template>
  <template v-else-if="kind==='kanban'"><form class="filters" @submit.prevent="addTask"><label>New task<input v-model="taskName" required maxlength="120" placeholder="What needs to happen?"></label><button type="submit">Add task</button></form><div class="kanban"><section v-for="column in ['Ready','In progress','Review']" :key="column" class="panel"><p class="eyebrow">{{ state.tasks.filter(task=>task.status===column).length }} TASKS</p><h2>{{ column }}</h2><article v-for="task in state.tasks.filter(task=>task.status===column)" :key="task.id" :data-task-id="task.id"><h3>{{ task.name }}</h3><label>Move task<select :value="task.status" :aria-label="`Move ${task.name}`" @change="move(task,$event.target.value)"><option>Ready</option><option>In progress</option><option>Review</option></select></label></article><p v-if="!state.tasks.some(task=>task.status===column)" class="muted">No tasks in this column.</p></section></div><p class="muted">Move tasks with the themed choice menu using the pointer or keyboard.</p></template>
  <section v-else class="panel empty"><h2>Application not found</h2><RouterLink to="/apps/email">Open email →</RouterLink></section>
</template>
