<script setup>
import { computed, reactive, ref, watch } from 'vue';
import { useRoute, useRouter } from 'vue-router';
import { state, recordKinds, nextId, notify } from '../store.js';
const route = useRoute(), router = useRouter(), query = ref(''), status = ref('all'), direction = ref(1), sort = ref('name'), page = ref(1);
const kind = computed(() => recordKinds[route.params.kind] ? route.params.kind : 'products');
const config = computed(() => recordKinds[kind.value]), records = computed(() => state.records[kind.value]);
const selected = computed(() => records.value.find(row => row.id === route.params.id));
const editing = computed(() => route.params.id === 'new' || route.params.action === 'edit');
const filtered = computed(() => records.value.filter(row => `${row.name} ${row.owner} ${row.id}`.toLowerCase().includes(query.value.toLowerCase()) && (status.value === 'all' || row.status === status.value)).sort((a,b) => (typeof a[sort.value] === 'number' ? a[sort.value]-b[sort.value] : a[sort.value].localeCompare(b[sort.value])) * direction.value));
const pages = computed(() => Math.max(1,Math.ceil(filtered.value.length / 5))), visible = computed(() => filtered.value.slice((page.value-1)*5,page.value*5));
const draft = reactive({ name: '', owner: '', status: 'Ready', amount: 0, note: '' });
watch(() => route.fullPath, () => { query.value='';status.value='all';page.value=1;Object.assign(draft, selected.value ?? { name: '', owner: 'Jordan Lee', status: 'Ready', amount: 0, note: '' }); }, { immediate:true });
watch([query,status], () => { page.value=1; });
function order(column) { if(sort.value===column)direction.value*=-1;else {sort.value=column;direction.value=1;} }
function save() { const row = { ...draft, amount:Number(draft.amount), id:selected.value?.id ?? nextId(records.value) }; if(selected.value)Object.assign(selected.value,row);else records.value.push(row); notify(`${config.value.singular} saved in this local demo.`);router.push(`/records/${kind.value}/${row.id}`); }
</script>
<template>
  <header class="view-heading"><div><p class="eyebrow">WORKSPACE / RECORDS</p><h1 tabindex="-1">{{ editing ? (selected ? 'Edit ' : 'New ') + config.singular.toLowerCase() : selected ? selected.name : config.title }}</h1><p>{{ editing ? 'Update the local record, then review the result.' : 'Search, inspect and edit synthetic application records.' }}</p></div><RouterLink v-if="!route.params.id" :to="`/records/${kind}/new`">+ New {{ config.singular.toLowerCase() }}</RouterLink><RouterLink v-else :to="`/records/${kind}`">← All {{ config.title.toLowerCase() }}</RouterLink></header>
  <form v-if="editing" class="panel form-grid" @submit.prevent="save"><j3w1-text-field><div class="text-field"><label class="text-field-label" for="record-name">{{ config.singular }} name</label><input class="text-field-input" id="record-name" name="name" v-model="draft.name" required maxlength="120"></div></j3w1-text-field><j3w1-text-field><div class="text-field"><label class="text-field-label" for="record-owner">Owner</label><input class="text-field-input" id="record-owner" name="owner" v-model="draft.owner" required></div></j3w1-text-field><j3w1-select><div class="select"><label class="select-label" for="record-status">Status</label><select class="select-control" id="record-status" v-model="draft.status" name="status"><option>Ready</option><option>In progress</option><option>Review</option></select></div></j3w1-select><label>{{ config.metric }} {{ config.unit }}<input v-model="draft.amount" type="number" name="amount" min="0" :step="kind==='users' ? 1 : .01" required></label><j3w1-textarea class="wide"><div class="textarea"><label class="textarea-label" for="record-note">Notes</label><textarea class="textarea-input" id="record-note" name="note" v-model="draft.note" rows="4"></textarea></div></j3w1-textarea><div class="actions wide"><j3w1-button><button class="button" type="submit">Save {{ config.singular.toLowerCase() }}</button></j3w1-button><RouterLink :to="selected ? `/records/${kind}/${selected.id}` : `/records/${kind}`">Cancel</RouterLink></div></form>
  <section v-else-if="selected" class="panel"><div class="panel-heading"><h2>{{ config.singular }} / {{ selected.id }}</h2><RouterLink :to="`/records/${kind}/${selected.id}/edit`">Edit record →</RouterLink></div><dl class="record-details"><dt>Name</dt><dd>{{ selected.name }}</dd><dt>Owner</dt><dd>{{ selected.owner }}</dd><dt>Status</dt><dd>{{ selected.status }}</dd><dt>{{ config.metric }}</dt><dd>{{ config.unit }}{{ selected.amount.toLocaleString() }}</dd><dt>Notes</dt><dd>{{ selected.note }}</dd></dl><template v-if="kind==='invoices'"><h3>Invoice preview</h3><p>Reference INV-{{ selected.id }} · sample line item · {{ config.unit }}{{ selected.amount.toFixed(2) }}</p><p class="muted">No payment processing, tax calculation or external delivery is performed.</p></template></section>
  <section v-else-if="route.params.id" class="panel empty"><h2>Record not found</h2><p>This record does not exist in the current local state.</p></section>
  <section v-else class="panel"><div class="filters"><label>Search {{ config.title.toLowerCase() }}<input type="search" v-model="query" placeholder="Name, owner or ID…"></label><label>Status<select v-model="status"><option value="all">All statuses</option><option>Ready</option><option>In progress</option><option>Review</option></select></label></div><div class="table-scroll" tabindex="0" role="region" :aria-label="`${config.title} table`"><table class="records-table"><thead><tr><th scope="col" :aria-sort="sort==='name' ? direction===1?'ascending':'descending' : 'none'"><button type="button" @click="order('name')">Name ↕</button></th><th scope="col">Owner</th><th scope="col">Status</th><th scope="col" :aria-sort="sort==='amount' ? direction===1?'ascending':'descending' : 'none'"><button type="button" @click="order('amount')">{{ config.metric }} ↕</button></th><th scope="col">Action</th></tr></thead><tbody><tr v-for="row in visible" :key="row.id"><td><RouterLink :to="`/records/${kind}/${row.id}`">{{ row.name }}</RouterLink><small class="block muted">{{ config.singular }} / {{ row.id }}</small></td><td>{{ row.owner }}</td><td :class="['status',row.status.toLowerCase()]">{{ row.status }}</td><td>{{ config.unit }}{{ row.amount.toLocaleString() }}</td><td><RouterLink :to="`/records/${kind}/${row.id}/edit`">Edit <span class="muted">{{ row.id }}</span></RouterLink></td></tr><tr v-if="!visible.length"><td colspan="5" class="empty">No matching records. Clear the search or choose another status.</td></tr></tbody></table></div><div class="panel-heading"><p role="status">{{ filtered.length }} records · Page {{ page }} of {{ pages }}</p><div class="actions"><button type="button" :disabled="page===1" @click="page--">← Previous</button><button type="button" :disabled="page===pages" @click="page++">Next →</button></div></div></section>
</template>
<style scoped>.record-details { display:grid;grid-template-columns:minmax(100px,1fr) 3fr;gap:16px;margin-block:28px; }.record-details dt { color:var(--color-text-muted); }.record-details dd { margin:0;overflow-wrap:anywhere; }</style>
