/* Builders for the agent-facing exports. Every export carries the theme
   name, version, profile and a source digest — never a timestamp or commit
   hash — so two runs on the same sources are byte-identical. */

import { POLICY_TEXT, releaseOf, eligibilityOf, eligibilityText } from "./eligibility.mjs";
import { sha256 } from "./fs.mjs";
import { extensionOf, toCss, statusOf } from "./tokens.mjs";
import { anchorFor, siteAnchor } from "./anchors.mjs";
import { sections, splitVariants } from "./spec.mjs";
import { portDownloadPath } from "./port-presentation.mjs";

const RAW = (manifest, rev) => manifest.sourceRevision.rawBase.replace("{rev}", rev);

export const tagFor = (manifest) => `v${manifest.version}`;

/* The region between <!-- @compact:start --> and <!-- @compact:end -->, or the whole body. */
export const compactRegion = (body) => {
  const m = body.match(/<!--\s*@compact:start\s*-->([\s\S]*?)<!--\s*@compact:end\s*-->/);
  return (m ? m[1] : body).trim();
};

/* The separator carries a NUL between entries, written as an escape so the
   file stays text; the string, and so every source digest, is unchanged. */
export const sourceDigestOf = (inputs) => sha256(inputs.map(([name, content]) => `${name}\n${content}`).join("\n\u0000\n"));

const header = ({ manifest, profileId, sourceDigest }) =>
  `<!-- generated by scripts/generate.mjs from tokens/ and spec/ — do not edit. theme: ${manifest.name} ${manifest.version} · profile: ${profileId} · sourceDigest: ${sourceDigest} -->`;

const CORE_GROUPS = ["surface", "text", "border", "interaction", "action", "status"];
/* Spacing, density and line heights are in the resolved tokens and every component JSON. */
const COMPACT_FOUNDATIONS = /^(border\.width\.|radius\.|font\.family\.|font\.size\.|focus\.|motion\.duration\.)/;

const roleRows = (resolved, { statuses, groups = null, profile = { status: "approved", default: true } }) => {
  const rows = [];
  for (const [path, token] of resolved) {
    if (!path.startsWith("color.") || path.startsWith("color.primitive.")) continue;
    if (groups && !groups.includes(path.split(".")[1])) continue;
    const status = statusOf(token);
    if (!statuses.includes(status)) continue;
    const decision = extensionOf(token)?.approval?.decision;
    const pending = `; ${eligibilityText(eligibilityOf(profile, token, resolved))}`;
    rows.push(`| \`${path}\` | \`${toCss(token.type, token.resolved)}\` | ${token.aliasOf ? `\`{${token.aliasOf}}\`` : "—"} | ${token.description ?? ""}${pending} |`);
  }
  return rows;
};

const foundationRows = (resolved, { filter = null } = {}) => {
  const rows = [];
  for (const [path, token] of resolved) {
    if (path.startsWith("color.")) continue;
    if (filter && !filter.test(path)) continue;
    rows.push(`| \`${path}\` | \`${toCss(token.type, token.resolved)}\` | ${token.description ?? ""} |`);
  }
  return rows;
};

export const shiftHeadings = (markdown, by = 1) => markdown.replace(/^(#{1,5}) /gm, (m, hashes) => `${"#".repeat(Math.min(6, hashes.length + by))} `);

const stateRulesOf = (component) => {
  const table = component.sections.get("States") ?? "";
  const rows = [];
  for (const line of table.split("\n")) {
    if (!line.startsWith("|") || /^\|\s*-/.test(line) || /^\|\s*state\s*\|/i.test(line)) continue;
    const cells = line.split("|").slice(1, -1).map((c) => c.trim());
    if (cells.length < 2) continue;
    const state = cells[0].replace(/`/g, "");
    const roles = component.stateTokens[state] ?? {};
    rows.push({ state, visual: cells[1], channel: cells[2] ?? "", tokens: roles });
  }
  return rows;
};

export const buildComponentJson = ({ manifest, profileId, sourceDigest, resolved, component, contrastPairs, coverage }) => {
  const profile = manifest.profiles.find((p) => p.id === profileId);
  const value = (path) => {
    const token = resolved.get(path);
    return token ? { alias: path, value: toCss(token.type, token.resolved), status: statusOf(token), deprecated: token.deprecated || false, decisionId: extensionOf(token)?.approval?.decision ?? null, eligibility: eligibilityOf(profile, token, resolved) } : { alias: path, value: null, status: "unresolved" };
  };
  const tokens = {};
  for (const [part, path] of Object.entries(component.tokens)) tokens[part] = value(path);
  return {
    schemaVersion: 1,
    theme: manifest.name,
    version: manifest.version,
    profile: profileId,
    profileStatus: profile.status,
    release: releaseOf(manifest.version),
    sourceDigest,
    id: component.id,
    family: component.family,
    maturity: component.maturity,
    priority: component.priority,
    coverage: coverage ?? null,
    title: component.name,
    summary: component.summary,
    anchors: {
      site: siteAnchor(manifest, anchorFor.component(component.id)),
      spec: component.file,
      brief: `exports/components/${component.id}.brief.txt`,
    },
    native: component.native,
    aria: component.aria,
    variants: component.variants,
    sizes: component.sizes,
    states: component.states,
    tokens,
    stateRules: stateRulesOf(component).map((row) => ({ ...row, tokens: Object.fromEntries(Object.entries(row.tokens).map(([k, v]) => [k, value(v)])) })),
    keyboard: component.keyboard,
    responsive: component.responsive,
    portability: component.portability,
    fixtures: component.fixtures,
    related: component.related,
    specimens: component.specimens,
    nonExamples: component.sections.get("Non-examples") ?? "",
    contrast: contrastPairs.filter((p) => p.source === component.id).map(({ label, state, kind, min, fg, bg, display, pass, waiver, fgPath, bgPath }) => ({ label, state, kind, min, fg: fgPath, bg: bgPath, fgHex: fg, bgHex: bg, ratio: Number(display), pass, waiver })),
  };
};

export const buildBrief = ({ manifest, profileId, sourceDigest, resolved, component }) => {
  const tag = tagFor(manifest);
  const lines = [
    `j3w1/theme implementation brief — ${component.id}`,
    `theme: ${manifest.name} ${manifest.version}  profile: ${profileId}  sourceDigest: ${sourceDigest}`,
    `pin: ${RAW(manifest, tag)}exports/components/${component.id}.json`,
    `spec: ${component.file}  site: ${siteAnchor(manifest, anchorFor.component(component.id))}`,
    `maturity: ${component.maturity}  priority: ${component.priority}`,
    "",
    `Summary: ${component.summary}`,
    "",
    POLICY_TEXT,
    "Tokens (resolved):",
  ];
  const width = Math.max(...Object.keys(component.tokens).map((k) => k.length));
  for (const [part, path] of Object.entries(component.tokens)) {
    const token = resolved.get(path);
    lines.push(`  ${part.padEnd(width)}  ${token ? toCss(token.type, token.resolved) : "?"}  ({${path}})  ${token ? eligibilityText(eligibilityOf(manifest.profiles.find((p) => p.id === profileId), token, resolved)) : "blocked"}`);
  }
  const pending = [...new Set(Object.values(component.stateTokens).flatMap((roles) => Object.values(roles)).flatMap((path) => eligibilityOf(manifest.profiles.find((p) => p.id === profileId), resolved.get(path), resolved).decisionIds))].sort();
  if (pending.length) lines.push(`State dependency disclosures: ${pending.join(", ")}`);
  lines.push("", `States: ${component.states.join(", ")}`);
  for (const row of stateRulesOf(component)) lines.push(`  ${row.state}: ${row.visual}${row.channel ? ` [${row.channel}]` : ""}`);
  if (component.keyboard.length) {
    lines.push("", "Keyboard:");
    for (const k of component.keyboard) lines.push(`  ${k.key}: ${k.action}`);
  }
  lines.push("", `ARIA: ${component.aria.pattern}${component.aria.apg ? ` (${component.aria.apg})` : ""}`);
  lines.push(`Responsive: ${component.responsive}`);
  lines.push(`Portability: ${component.portability.web}`);
  for (const fallback of component.portability.nativeFallbacks) lines.push(`  native: ${fallback}`);
  lines.push("", "Rules: use only these values; no invented colours; radius 0; borders 1px (2px emphasis); focus is a 1px dashed ring, selection is a fill;",
    "do not restyle unrelated elements; report deviations per agents/consume.md; record theme.lock.json at the pinned revision.");
  return `${lines.join("\n")}\n`;
};

export const buildCompact = ({ manifest, profileId, sourceDigest, resolved, docs, components, coverage }) => {
  const identity = docs.find((d) => d.id === "identity");
  const foundations = docs.find((d) => d.id === "foundations");
  const tag = tagFor(manifest);
  const raw = RAW(manifest, tag);
  const out = [
    `# j3w1 UI Theme Spec — compact (${manifest.version}, profile: ${profileId})`,
    header({ manifest, profileId, sourceDigest }),
    "",
    "Read this first; it is the smallest complete statement of the approved contract.",
    `Pin a tag or commit and fetch every file at that revision (see \`agents/consume.md\`). Values marked PROPOSED are not approved.`,
    "",
    POLICY_TEXT,
    "## Identity",
    "",
    compactRegion(identity.body),
    "",
    `## Approved core roles (${profileId})`,
    "",
    "Surfaces, text, borders, interaction, actions and status. The code, diagnostic, diff, terminal, chart and icon groups are in `exports/tokens.resolved.json` and inlined in each component's JSON.",
    "",
    "| Role | Value | Alias of | Use |",
    "| --- | --- | --- | --- |",
    ...roleRows(resolved, { statuses: ["observed", "approved", "site-specific", "heritage"], groups: CORE_GROUPS }),
    "",
    "## Foundations",
    "",
    "| Token | Value | Use |",
    "| --- | --- | --- |",
    ...foundationRows(resolved, { filter: COMPACT_FOUNDATIONS }),
    "",
    "## State rules",
    "",
    compactRegion(foundations.body),
    "",
    "## Component briefs",
    "",
  ];
  const proposed = roleRows(resolved, { statuses: ["proposed"], groups: CORE_GROUPS });
  for (const component of components.filter((c) => c.compact)) {
    const cov = coverage?.[component.id];
    out.push(`### ${component.id} — ${component.name}`, "");
    out.push(`${component.summary} Status: ${cov ? [cov.specified && "specified", cov.demonstrated && "demonstrated", cov.testImplemented && "test implemented"].filter(Boolean).join(", ") : component.maturity}. Site: ${siteAnchor(manifest, anchorFor.component(component.id))}. JSON: \`exports/components/${component.id}.json\`.`, "");
    out.push(`States: ${component.states.join(", ")}.`, "");
    const tokenLines = Object.entries(component.tokens).map(([part, path]) => {
      const token = resolved.get(path);
      return `${part} → \`${path}\` (${token ? toCss(token.type, token.resolved) : "?"})`;
    });
    out.push(`Tokens: ${tokenLines.join("; ")}.`, "");
  }
  if (proposed.length) {
    out.push(
      "## Roles pending an owner decision",
      "",
      "These roles use-and-report their pending decision IDs at the pinned revision; their proposed status is unchanged.",
      "",
      "| Role | Value | Alias of | Use |",
      "| --- | --- | --- | --- |",
      ...proposed,
      "",
    );
  }
  out.push(
    "## Where to read more",
    "",
    `- Reading protocol: ${raw}agents/consume.md`,
    `- Manifest: ${raw}theme.json`,
    `- Resolved tokens: ${raw}exports/tokens.resolved.json`,
    `- Per-component JSON: ${raw}exports/components/<id>.json`,
    `- Full specification: ${raw}exports/theme.full.md`,
    `- Digests: ${raw}exports/digests.json`,
    `- Site (confirmation only): ${manifest.site.url}`,
    "",
  );
  return out.join("\n");
};

export const buildFull = ({ manifest, profileId, sourceDigest, profiles, docs, components, families, coverage, contrastPairs, ports, catalogue, decisionsMarkdown }) => {
  const byId = (id) => docs.find((d) => d.id === id);
  const out = [
    `# j3w1 UI Theme Spec — full (${manifest.version})`,
    header({ manifest, profileId, sourceDigest }),
    "",
    POLICY_TEXT,
    "Everything in one document: identity, foundations, every profile's resolved tokens, accessibility with the contrast report, portability, every component specification, the coverage ledger, the support table, the decision log and the references catalogue.",
    "",
    "## Identity", "", byId("identity").body.trim(), "",
    "## Foundations", "", shiftHeadings(byId("foundations").body.trim()), "",
  ];
  for (const profile of manifest.profiles) {
    const resolved = profiles.get(profile.id);
    out.push(`## Tokens — profile \`${profile.id}\` (${profile.status})`, "", "| Role | Value | Alias of | Use |", "| --- | --- | --- | --- |", ...roleRows(resolved, { statuses: ["observed", "approved", "site-specific", "heritage"], profile }), "");
    const proposed = roleRows(resolved, { statuses: ["proposed"], profile });
    if (proposed.length) out.push(`### Roles pending an owner decision in \`${profile.id}\``, "", "| Role | Value | Alias of | Use |", "| --- | --- | --- | --- |", ...proposed, "");
    if (profile.id === profileId) out.push("### Foundations", "", "| Token | Value | Use |", "| --- | --- | --- |", ...foundationRows(resolved), "");
  }
  out.push("## Accessibility", "", shiftHeadings(byId("accessibility").body.trim()), "", "### Contrast report", "", ...contrastTable(contrastPairs), "");
  out.push("## Portability", "", shiftHeadings(byId("portability").body.trim()), "");
  for (const family of families) {
    const members = components.filter((c) => c.family === family.id).sort((a, b) => a.order - b.order);
    if (!members.length) continue;
    out.push(`## ${family.title}`, "", family.description, "");
    for (const component of members) {
      const resolved = profiles.get(profileId);
      out.push(`### ${component.name} (\`${component.id}\`)`, "", `${component.summary} Family: ${family.id}. Priority: ${component.priority}. Maturity: ${component.maturity}. States: ${component.states.join(", ")}.`, "");
      out.push("| Part | Role | Value | Eligibility |", "| --- | --- | --- | --- |");
      for (const [part, path] of Object.entries(component.tokens)) {
        const token = resolved.get(path);
        out.push(`| ${part} | \`${path}\` | \`${token ? toCss(token.type, token.resolved) : "?"}\` | ${token ? eligibilityText(eligibilityOf(manifest.profiles.find((p) => p.id === profileId), token, resolved)) : "blocked"} |`);
      }
      out.push("", shiftHeadings(component.body.trim(), 2), "");
    }
  }
  out.push("## Coverage ledger", "", ...coverageTable(components, coverage), "");
  out.push("## Application ports", "", ...portsTable(ports), "", "### Downloads", "", ...downloadsTable(manifest, ports), "");
  out.push("## Decisions", "", shiftHeadings(decisionsMarkdown.trim()), "");
  out.push("## References", "", ...catalogueTable(catalogue), "");
  return `${out.join("\n")}\n`;
};

export const contrastTable = (pairs) => [
  "| Pair | State | Kind | Foreground | Background | Ratio | Minimum | Result |",
  "| --- | --- | --- | --- | --- | --- | --- | --- |",
  ...pairs.map((p) => `| ${p.label ?? p.source} | ${p.state ?? "—"} | ${p.kind} | \`${p.fgPath}\` ${p.fg} | \`${p.bgPath}\` ${p.bg} | ${p.display} | ${p.min} | ${p.pass ? "pass" : p.waiver ? `waived: ${p.waiver}` : "**fail**"} |`),
];

export const coverageTable = (components, coverage) => [
  "| Component | Family | Priority | Specified | Demonstrated | Test implemented |",
  "| --- | --- | --- | --- | --- | --- |",
  ...components.map((c) => {
    const cov = coverage[c.id];
    const mark = (v) => (v ? "yes" : "—");
    return `| \`${c.id}\` | ${c.family} | ${c.priority} | ${mark(cov.specified)} | ${mark(cov.demonstrated)} | ${mark(cov.tested)} |`;
  }),
];

export const portsTable = (ports) =>
  ports.length
    ? [
        "| Port | Format | Declared status | Import evidence | Theme | Tested on | Supported / inherited / unsupported |",
        "| --- | --- | --- | --- | --- | --- | --- |",
        ...ports.map((p) => `| ${p.displayName} | ${p.format} | ${p.status} | ${p.verification?.status ?? "not verified"} | ${p.themeVersion} | ${p.testedVersions.join(", ") || "—"} (${p.os.join(", ")}) | ${p.surfaces.supported.length} / ${p.surfaces.inherited.length} / ${p.surfaces.unsupported.length} |`),
      ]
    : ["No native ports are published yet. Historical implementations are catalogued in `references/` and are not supported downloads."];

/* One row per importable file: a raw link pinned to this version's tag and
   the copy the site serves. Neither ever names a branch. */
export const downloadsTable = (manifest, ports) =>
  ports.some((p) => p.files.length)
    ? [
        `| Application | File (theme ${manifest.version}) | Also on the site | Install | Status |`,
        "| --- | --- | --- | --- | --- |",
        ...ports.flatMap((p) => p.files.map((f) => `| ${p.displayName} | [${f.path.split("/").at(-1)}](${RAW(manifest, tagFor(manifest))}ports/${p.id}/${f.path}) | [download](${manifest.site.url}${portDownloadPath(p.id, f.path)}) | ${f.install} | ${p.status}; import evidence ${p.verification?.status ?? "not verified"} |`)),
      ]
    : ["No application theme files are published yet."];

export const catalogueTable = (catalogue) => [
  "| Reference | Kind | Where | What it does not prove |",
  "| --- | --- | --- | --- |",
  ...catalogue.entries.map((e) => `| ${e.title} | ${e.kind} | ${e.source ? `\`${e.source.repository}\` \`${e.source.path}\`` : `\`${e.path}\``} | ${e.notes} |`),
];

export const buildLlms = ({ manifest }) => {
  const tag = tagFor(manifest);
  const raw = RAW(manifest, tag);
  return [
    "# j3w1 UI Theme Spec",
    "",
      `> Versioned design tokens and component rules for the j3w1 identity: True Black / Rose, rose foregrounds, dark-red actions, square borders and monospace typography. Version ${manifest.version}. Agents: use pinned canonical contracts and official package or complete copy distributions.`,
    "",
    "Pin a tag or commit and use the same revision for every file. Never read `main`.",
    "",
    "## Start here",
    "",
    `- [Reading protocol](${raw}agents/consume.md): the seven steps, what you may not do, the lock and report formats`,
    `- [Manifest](${raw}theme.json): profiles, entry points, export paths`,
      `- [Compact spec](${raw}exports/theme.compact.md): approved values, state rules, ten component briefs`,
      `- [Implementation index](${raw}packages/ui/dist/index.json): bounded discovery for all 67 official implementations`,
      `- [Consumption guide](${raw}docs/ui-consumption.md): package, copy and mapping modes in HTML, Vue, React and Astro`,
      `- [Implementation manifest](${raw}packages/ui/dist/manifest.json): APIs, dependency closures, copy file digests and canonical links; actual execution evidence is separate`,
    "",
    "## Data",
    "",
    `- [Resolved tokens](${raw}exports/tokens.resolved.json): every profile, every alias resolved`,
    `- [Token CSS](${raw}exports/tokens.css): the same values as custom properties`,
    `- [Component JSON](https://github.com/j3w1/theme/tree/${tag}/exports/components): one file per component`,
    `- [Digests](${raw}exports/digests.json): sha256 per export for theme.lock.json`,
    "",
    "## Optional",
    "",
    `- [Full spec](${raw}exports/theme.full.md): everything concatenated`,
    `- [Contrast report](${raw}exports/contrast.md): every declared pair, unrounded`,
    `- [Website](${manifest.site.url}): rendered specimens for visual confirmation`,
    "",
  ].join("\n");
};

export const demoVariantsOf = (component) => (component.demo ? [...splitVariants(component.demo).keys()] : []);

export { sections };
